### ISSUE TITLE
doesn't work in edge

### ISSUE THREAD

**Issue by SunBlazes** [ariburaco/chatgpt-file-uploader-extended#13]
Hi,I am appreciated for your work,but I find that it disappears in gpt page as well as becomes grey in edge extension.

**Comment by Nonmy** [comment]
Neither in chrome， installed from webstore

**Comment by ariburaco** [comment]
the v1.4 should fix the issue, but it is not published on chrome store yet.

<img width="843" alt="image" src="https://github.com/ariburaco/chatgpt-file-uploader-extended/assets/34109588/84593f4c-954e-418d-8cbd-c0f9ec23c7dc">
