### ISSUE TITLE
Does this tool currently support the Chrome browser on macOS ?

### ISSUE THREAD

**Issue by KyleChang95** [ariburaco/chatgpt-file-uploader-extended#14]
Hello,

First of all, I would like to express my appreciation for developing this incredibly convenient tool. I'm reaching out here to inquire whether this tool currently supports the Chrome browser on macOS. On the Windows system, I have been able to use the tool normally, but when I attempted to use it on my MacBook, I encountered an issue where the upload and configuration buttons are not being displayed.

Although I have tried reinstalling the tool, the issue still persists. Here are the detailed specifications of my environment:

- MacBook Pro 13-inch, 2017 model
- macOS Ventura 13.1
- Chrome browser 115.0.5790.170 (x86_64)

I would greatly appreciate it if you could provide assistance and guidance on this issue. Thank you in advance for your response.

![image](https://github.com/ariburaco/chatgpt-file-uploader-extended/assets/14266557/c254c484-c401-4453-9f27-4c926f84c3a3)

**Comment by ariburaco** [comment]
I've made an update to fix this issue-v1.4, and it is still pending review on chrome store.

**Comment by KyleChang95** [comment]
Thank you.
